### ISSUE TITLE
blog: Provable Optimization with Microsoft Z3; update full solution link

### ISSUE THREAD

**Issue by brrgrl** [CraigStuntz/CraigStuntz.github.io#1]
In your blog post, [Provable Optimization with Microsoft Z3](https://www.craigstuntz.com/posts/2015-03-05-provable-optimization-with-microsoft-z3.html), you linked to a [rise4fun solution link](http://rise4fun.com/Z3/7VZh) 
`Z3/SMT-LIB doesn’t ship with a digit-sum function, so I had to write that. You can find that code in the full solution, below.`
but [rise4fun is down](https://github.com/Z3Prover/z3/discussions/5473).

I'm interested in how you defined the `digit-sum` function. Could you please update the blog post?

Thank you,
Andrew

**Comment by CraigStuntz** [comment]
The full solution was: 
```smt-lib
; Write a Ruby program that determines the smallest three digit number 
; such that when said number is divided by the sum of its digits 
; the answer is 20.
(define-fun hundreds  ((n Int)) Int (div n 100))
(define-fun tens      ((n Int)) Int (div (- n (* 100 (hundreds n))) 10))
(define-fun ones      ((n Int)) Int (mod n 10))
(define-fun digit-sum ((n Int)) Int (+ (hundreds n) (tens n) (ones n)))
(define-fun matches-problem ((n Int)) Bool
  (and 
    (>= n 100) 
    (< n 1000)                   ; three digits
    (= 20.0 (/ n (digit-sum n)))))
(declare-const num Int)
(assert 
  (and 
    (matches-problem num)
    (forall ((other Int)) (implies (matches-problem other) (>= other num))) ; no smaller answer
  ))
(check-sat)
(get-model)
```
I will append this to the blog post soon. Thanks!

**Comment by brrgrl** [comment]
Nice it works! 
```
Compilation started at Fri May 10 20:12:05

z3 -smt2 small.smt2
sat
(
  (define-fun num () Int
    180)
  (define-fun /0 ((x!0 Real) (x!1 Real)) Real
    (ite (and (= x!0 80.0) (= x!1 8.0)) 10.0
      20.0))
)
```

thank you so much! this helps while I try to learn z3
